"use client";

import type { Transaction } from "@/types/transaction";
import { Card, CardContent, CardHeader } from "../ui/card";
import { useEffect, useState } from "react";

const SummaryAI = ({ transactions }: { transactions: Transaction[] }) => {
  const [summary, setSummary] = useState("");

  useEffect(() => {
    console.debug("🚀 ~ SummaryAI.tsx:10 ~ SummaryAI ~ summary:", summary);
  }, [summary]);

  useEffect(() => {
    const prompt = `
    You are a financial assistant.
    You are given a list of transactions and you need to generate a summary of the transactions.
    The transactions are:
    ${transactions
      .map(
        (transaction) =>
          `${transaction.date} - ${transaction.content} - ${transaction.amount}`
      )
      .join("\n")}
    Please provide a 100-word summary of the transaction data.
    `;

    const fetchSummary = async () => {
      const res = await fetch("api/openai", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ prompt }),
      });
      const data = await res.json();

      console.debug("🚀 ~ SummaryAI.tsx:34 ~ fetchSummary ~ summary:", data);

      setSummary(data.result.content);
    };

    fetchSummary();
  }, [transactions]);

  return (
    <Card className="flex flex-row">
      <div className="w-1/2">
        <CardHeader>AI Summary</CardHeader>
        <CardContent>
          <p>{summary}</p>
        </CardContent>
      </div>
      <div className="w-1/2">
        <CardHeader>AI Advice</CardHeader>
        <CardContent>
          <p>
            a This is a summary of your transactions. It is generated by an AI
            assistant.
          </p>
        </CardContent>
      </div>
    </Card>
  );
};

export default SummaryAI;
